services:
  - type: worker
    name: red-discordbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    disk:
      name: red-data
      mountPath: /opt/render/project/data
      sizeGB: 1
